/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
import type * as mocks from "./mocks";
export type { mocks };
export type { ERC721BO } from "./ERC721BO";
export type { IERC721BO } from "./IERC721BO";
