/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControlMock } from "./AccessControlMock";
export type { AssetsMock } from "./AssetsMock";
export type { BitsMock } from "./BitsMock";
export type { CounterMock } from "./CounterMock";
export type { ERC721BOMock } from "./ERC721BOMock";
export type { ERC721BONonburnableMock } from "./ERC721BONonburnableMock";
export type { ERC721ReceiverMock } from "./ERC721ReceiverMock";
export type { OwnersMock } from "./OwnersMock";
